#!/bin/bash

icondir="$HOME/.config/mako/icons"

get_percentage_backlight() {
    current_brightness="$(brightnessctl g)"
    max_brightness="$(brightnessctl m)"
    percentage_brightness=$((current_brightness * 100 / max_brightness))
    # round to 10
    echo $((((percentage_brightness + 5) / 10) * 10))
}

# Get icons
get_icon() {
    backlight="$(brightnessctl g)"
    current="${backlight%%%}"
    if [[ ("$current" -ge "0") && ("$current" -le "51") ]]; then
        icon="$icondir/brightness-20.png"
    elif [[ ("$current" -ge "51") && ("$current" -le "102") ]]; then
        icon="$icondir/brightness-40.png"
    elif [[ ("$current" -ge "102") && ("$current" -le "153") ]]; then
        icon="$icondir/brightness-60.png"
    elif [[ ("$current" -ge "153") && ("$current" -le "204") ]]; then
        icon="$icondir/brightness-80.png"
    elif [[ ("$current" -ge "204") && ("$current" -le "255") ]]; then
        icon="$icondir/brightness-100.png"
    fi
}

# Notify
notify_user() {
    notify-send \
        -h string:synchronous:brightness-change \
        -u low \
        -i "$icon" "Helligkeit : $(get_percentage_backlight)"
}

# Increase brightness
inc_backlight() {
    brightnessctl set 10%+ && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
    brightnessctl set 10%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
    brightnessctl g
elif [[ "$1" == "--inc" ]]; then
    inc_backlight
elif [[ "$1" == "--dec" ]]; then
    dec_backlight
else
    brightnessctl i
fi

# vim:set ts=4 sw=4 et:
