#!/bin/sh
# "Change keyboard layout in" "~/.config/hypr/hyprland.conf" " " \

yad --width=450 --height=550 \
--center \
--fixed \
--title="Hyprland Tastenkombinationen" \
--no-buttons \
--list \
--column=Tastenkombination: \
--column=Beschreibung: \
--timeout=60 \
--timeout-indicator=right \
" 󰐕 ␣" "Programmstarter" \
" 󰐕 ↑ 󰐕 ↲" "Dateiverwaltung" \
" 󰐕 F" "Browser" \
" 󰐕 ↲" "Terminal" \
"" "" \
" 󰐕 ↑ 󰐕 F" "Vollbild" \
" 󰐕 V" "Schweben" \
" 󰐕 J" "Fenster anordnen" \
" 󰐕 Q" "Schliesse Fenster" \
"" "" \
"ALT 󰐕 V" "Zwischenablage" \
" 󰐕 S" "Screenshot" \
"" "" \
" 󰐕 L" "Bildschirm Sperren" \
" 󰐕 M" "Abmelden" \
"" "" \
"ESC" "Schliesse dieses Fenster" \

